apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keeper-pdb
  namespace: clickhouse
spec:
  minAvailable: 2
  selector:
    matchLabels:
      clickhouse-keeper.altinity.com/chi: keeper
