apiVersion: v1
kind: Service
metadata:
  name: ipfix-collector
  namespace: {{ .Values.ipfix.namespace }}
  labels:
    app: ipfix-collector
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ipfix-collector
  ports:
  - name: ipfix
    port: {{ .Values.ipfix.listenPort }}
    protocol: UDP
