apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: server
  namespace: clickhouse
spec:
  taskID: "1"

  configuration:
    # No Keeper here for base config (single node / non-replicated)

    users:
      # Disable dangerous defaults; create reader/writer explicitly.
      default/readonly: 1

      writer/password_sha256_hex:
        valueFrom:
          secretKeyRef:
            name: clickhouse-db-passwords
            key: writer_password_sha256
      writer/profile: default
      writer/quota: default
      writer/networks/ip: "::/0"

      reader/password_sha256_hex:
        valueFrom:
          secretKeyRef:
            name: clickhouse-db-passwords
            key: reader_password_sha256
      reader/profile: readonly
      reader/quota: default
      reader/networks/ip: "::/0"

    profiles:
      readonly/readonly: 1

    clusters:
      - name: c
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: ch-pod
          volumeClaimTemplate: ch-data

  templates:
    podTemplates:
      - name: ch-pod
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/worker
                        operator: In
                        values:
                          - worker
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      clickhouse.altinity.com/chi: ch
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse
              # Injected by envsubst in install script from helm-chart-versions.yaml
              image: ${CLICKHOUSE_SERVER_IMAGE}
              imagePullPolicy: IfNotPresent
              ports:
                - name: http
                  containerPort: 8123
                - name: native
                  containerPort: 9000
                - name: inter
                  containerPort: 9009
    volumeClaimTemplates:
      - name: ch-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: general
          resources:
            requests:
              storage: 10Gi
