apiVersion: v1
kind: Service
metadata:
  name: clickhouse-http
  namespace: clickhouse
  labels:
    app: clickhouse
spec:
  type: ClusterIP
  selector:
    clickhouse.altinity.com/chi: ch
  ports:
    - name: http
      port: 8123
      targetPort: 8123
